import type { Metadata } from "next";
import { Red_Hat_Text } from "next/font/google";
import cn from "classnames";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const redHatText = Red_Hat_Text({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "James Kakivelis's Website",
  description: "A website created by James Kakivelis. Originally generated by create next app.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicon/site.webmanifest" />
        <link
          rel="mask-icon"
          href="/favicon/icon.svg"
          color="#008cffff"
        />
        <link rel="shortcut icon" href="/favicon/favicon.ico" />
        <meta name="msapplication-TileColor" content="#008cffff" />
        <meta
          name="msapplication-config"
          content="/favicon/browserconfig.xml"
        />
      </head>
      <body className={cn(redHatText.className)}>
        <Header />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
